/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Connection.SqlHandler;
import controllers.MainController;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import utils.POCException;

/**
 *
 * @author samuelhendrykus
 */
public class FindToko extends javax.swing.JFrame {
    private MainController mainController;
    private SqlHandler handler;
    DefaultTableModel tablemodel;
    JTable table;
    /**
     * Creates new form FindToko
     */
    public FindToko(MainController mainController, SqlHandler handler) {
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e){
            JOptionPane.showMessageDialog(this, "Failed to set Look and Feel", "GUI Exception", JOptionPane.WARNING_MESSAGE);
        }
        
        initComponents();
        
        mainController = mainController;
        this.handler = handler;
        
        try{
            this.setIconImage(mainController.getIconImage());
        }catch(POCException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), e.getTitle(), JOptionPane.WARNING_MESSAGE);
        }
        this.setTitle("Cari Toko");
        
        // launch the window  
      
        pack();
        validate();
        setLocationRelativeTo(null);    // centering the window
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
    }
    
    public void initTable() 
    {
        tablemodel = new DefaultTableModel();
        this.table = new JTable(tablemodel) 
        {
            @Override
            public boolean isCellEditable(int row, int column) {
                if (column == 3) {
                    return true;
                }
                return false;
            }
        };
        tablemodel.addColumn("ID Toko");
        tablemodel.addColumn("ID Departemen");
        tablemodel.addColumn("Nama Toko");
        tablemodel.addColumn("Alamat");
        tablemodel.addColumn("Telepon");     
        this.resultPanel.add(this.table);
        this.resultPanel.setViewportView(this.table);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cariBerdasarkan = new javax.swing.JLabel();
        field = new javax.swing.JComboBox();
        nilai = new javax.swing.JLabel();
        value = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        resultPanel = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        cariBerdasarkan.setText("Cari Berdasarkan");

        field.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Id Toko", "Id Departemen", "Nama Toko", "Alamat", "Telepon" }));

        nilai.setText("Nilai");

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cariBerdasarkan)
                            .addComponent(nilai))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(field, 0, 406, Short.MAX_VALUE)
                            .addComponent(value)))
                    .addComponent(cari)
                    .addComponent(resultPanel))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cariBerdasarkan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nilai)
                    .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cari)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        try {
            // TODO add your handling code here:
            handler.connectToDataBase();
            ResultSet result = handler.findProduk(this.field.getSelectedItem().toString(), this.value.getText());
            while(result.next()){
                this.tablemodel.addRow(new Object[]{result.getString(0), result.getString(1), result.getString(2), result.getString(3), result.getString(4)});
            }
        } catch (Exception ex) {
            Logger.getLogger(FindProductUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cariActionPerformed


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JLabel cariBerdasarkan;
    private javax.swing.JComboBox field;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nilai;
    private javax.swing.JScrollPane resultPanel;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
