/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import Connection.SqlHandler;
import controllers.MainController;
import javax.swing.*;
import utils.POCException;

/**
 *
 * @author samuelhendrykus
 */
public class MainWindow extends javax.swing.JFrame {
    ImageIcon icon;
    private MainController mainController;
    private SqlHandler handler;
    /**
     * Creates new form MainWindow
     */
    public MainWindow(MainController main, SqlHandler handler) {
        try{
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }catch(ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e){
            JOptionPane.showMessageDialog(this, "Failed to set Look and Feel", "GUI Exception", JOptionPane.WARNING_MESSAGE);
        }
        initComponents();
        mainController = main;
        this.handler = handler;
        
        icon = new ImageIcon("images\\carrefourlogo.jpg");
        this.LogoPanel.add(new Logo(icon.getImage()));
        this.LogoPanel.repaint();
        
        this.setTitle("PO Converter");
        
        // launch the window  
        try{
            this.setIconImage(mainController.getIconImage());
//            this.setIconImage(new ImageIcon(getClass().getResource("/abc/icon.png")).getImage());
        }catch(POCException e){
            JOptionPane.showMessageDialog(this, e.getMessage(), e.getTitle(), JOptionPane.WARNING_MESSAGE);
        }
        pack();
        validate();
        //setExtendedState(Frame.MAXIMIZED_BOTH);   // for full screen
        setLocationRelativeTo(null);    // centering the window
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//        setSize(500, 500);
        setVisible(true);       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelBrand1 = new javax.swing.JLabel();
        labelBrand2 = new javax.swing.JLabel();
        LogoPanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        POConverterMenu = new javax.swing.JMenu();
        BuatOrder = new javax.swing.JMenuItem();
        Pengaturan = new javax.swing.JMenuItem();
        ProdukMenu = new javax.swing.JMenu();
        TambahProduk = new javax.swing.JMenuItem();
        CariProduk = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        labelBrand1.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        labelBrand1.setText("PO Converter");

        labelBrand2.setFont(new java.awt.Font("Trajan Pro", 0, 11)); // NOI18N
        labelBrand2.setText("| by Aristophanes A. Alvin & Samuel Hendrykus S. 2014");

        LogoPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout LogoPanelLayout = new javax.swing.GroupLayout(LogoPanel);
        LogoPanel.setLayout(LogoPanelLayout);
        LogoPanelLayout.setHorizontalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        LogoPanelLayout.setVerticalGroup(
            LogoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 273, Short.MAX_VALUE)
                        .addComponent(labelBrand1)
                        .addGap(45, 45, 45)
                        .addComponent(labelBrand2))
                    .addComponent(LogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LogoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelBrand1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBrand2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        FileMenu.setText("File");
        jMenuBar1.add(FileMenu);

        jMenu3.setText("Pesanan");

        jMenuItem5.setText("Pesanan");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        POConverterMenu.setText("PO Converter");
        POConverterMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POConverterMenuActionPerformed(evt);
            }
        });

        BuatOrder.setText("Buat Order");
        BuatOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuatOrderActionPerformed(evt);
            }
        });
        POConverterMenu.add(BuatOrder);

        Pengaturan.setText("Pengaturan");
        Pengaturan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PengaturanActionPerformed(evt);
            }
        });
        POConverterMenu.add(Pengaturan);

        jMenuBar1.add(POConverterMenu);

        ProdukMenu.setText("Produk");

        TambahProduk.setText("Tambah Produk");
        TambahProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahProdukActionPerformed(evt);
            }
        });
        ProdukMenu.add(TambahProduk);

        CariProduk.setText("Cari Produk");
        CariProduk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariProdukActionPerformed(evt);
            }
        });
        ProdukMenu.add(CariProduk);

        jMenuBar1.add(ProdukMenu);

        jMenu1.setText("Supplier");

        jMenuItem1.setText("Tambah Supplier");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Cari Supplier");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Toko");

        jMenuItem3.setText("Tambah Toko");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Cari Toko");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuatOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuatOrderActionPerformed
        // TODO add your handling code here:
        POMain po = new POMain(this.mainController);
        
        
    }//GEN-LAST:event_BuatOrderActionPerformed

    private void POConverterMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POConverterMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_POConverterMenuActionPerformed

    private void PengaturanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PengaturanActionPerformed
        // TODO add your handling code here:
        POSetting setting = new POSetting(this.mainController);
    }//GEN-LAST:event_PengaturanActionPerformed

    private void TambahProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahProdukActionPerformed
        // TODO add your handling code here:
        ProdukUI produk = new ProdukUI(mainController, handler);
    }//GEN-LAST:event_TambahProdukActionPerformed

    private void CariProdukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariProdukActionPerformed
        // TODO add your handling code here:
        FindProductUI ui = new FindProductUI(mainController, handler);
    }//GEN-LAST:event_CariProdukActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        AddSupplier ui = new AddSupplier(mainController, handler);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        FindSupplier ui = new FindSupplier(mainController, handler);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        addToko ui = new addToko(mainController, handler);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        FindToko ui = new FindToko(mainController, handler);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        Pesanan ui = new Pesanan(mainController, handler);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BuatOrder;
    private javax.swing.JMenuItem CariProduk;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JPanel LogoPanel;
    private javax.swing.JMenu POConverterMenu;
    private javax.swing.JMenuItem Pengaturan;
    private javax.swing.JMenu ProdukMenu;
    private javax.swing.JMenuItem TambahProduk;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelBrand1;
    private javax.swing.JLabel labelBrand2;
    // End of variables declaration//GEN-END:variables
}
